apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: {{ .Values.frontend.name }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Values.frontend.name }}
              servicePort: {{ .Values.frontend.service.port }}
