apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.backend.name }}
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Values.backend.name }}
  type: {{ .Values.backend.service.type }}
    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.frontend.name }}
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: {{ .Values.frontend.name }}
  type: {{ .Values.frontend.service.type }}