apiVersion: v1
kind: Service
metadata:
  labels:
    app: dynamodb
  name: dynamodb
  namespace: "vote-dog-cat-api"
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: dynamodb
    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: "vote-dog-cat-api"
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: frontend
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend2
  name: frontend2
  namespace: "vote-dog-cat-api"
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: frontend2
  type: NodePort