apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.backend.name }}
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    app: {{ .Values.backend.name }}
  type: {{ .Values.backend.service.type }}
    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.frontend.name }}
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: {{ .Values.frontend.name }}
  type: {{ .Values.frontend.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.frontend2.name }}
  name: {{ .Values.frontend2.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.frontend2.service.port }}
    targetPort: {{ .Values.frontend2.service.targetPort }}
  selector:
    app: {{ .Values.frontend2.name }}
  type: {{ .Values.frontend2.service.type }}