apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vote-dog-cat-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2
  namespace: vote-dog-cat-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate